### PR TITLE
fix invalid json if needed only

### PR DESCRIPTION
**Pull request by ms-slasher13**
### Overview
see https://github.com/drush-ops/drush/pull/3931#issuecomment-467953232

### CODE REVIEW

**Comment by weitzman** [comment]
Thanks. I'm a little confused about why the output needs to fixed up at all. Most escaping that I've seen is only for the CLI and by the time PHP receives the arguments, the data is already "unescaped". It appears that our Windows escaping needs unescaping. Is it possible to avoid that? If not, maybe there should be a static method for unescaping?

**Comment by greg-1-anderson** [comment]
I am -1 on speculative or conditional correction. It seems to me that json_encode / json_decode should be symmetric on Windows. I'm not sure where in the output of the json additional escaping might happen if not in json_encode. If an asymmetrical adjustment is needed (e.g. extra unescaping on the Windows platform), then we should either do that or not. Conditionalizing based on whether json_decode works or not runs the risk of creating ambiguous behavior on the Windows platform.

**Comment by ms-slasher13** [comment]
I'm also confused. Add logging at this point to find all processes which are handled differently might help. No time and no better idea in the moment.

**Comment by greg-1-anderson** [comment]
In fixing up other unrelated problems with json escaping, I made the Windows tests much worse. I don't have a Windows system to test on, and I'm not sure how to explain the behavior I was seeing on AppVeyor, so I simply disabled the Windows tests for now.

If you are inclined to continue here, it would be appreciated.

**Pull request closed without merging**
